### ISSUE TITLE
Error when try create a page: Class 'String' has no instance method '[]='

### ISSUE THREAD

**Issue by JacquesMarques** [Flutterando/slidy#239]
When I try create a page with the command:
 slidy generate page modules/start

Unhandled exception:
NoSuchMethodError: Class 'String' has no instance method '[]='.
Receiver: "true"
Tried calling: []=("image_path", Instance of 'Line')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      PubspecServiceImpl.loadYaml (package:slidy/src/core/services/pubspec_service_impl.dart:42:40)
<asynchronous suspension>
#2      PubspecServiceImpl.getLine (package:slidy/src/core/services/pubspec_service_impl.dart:195:19)
<asynchronous suspension>
#3      TemplateFile.getInstance (file:///home/jacques/.pub-cache/hosted/pub.dartlang.org/slidy-3.0.0+2/bin/utils/template_file.dart:26:64)
<asynchronous suspension>
#4      GeneratePageSubCommand.run (file:///home/jacques/.pub-cache/hosted/pub.dartlang.org/slidy-3.0.0+2/bin/commands/sub_command/generate_page_sub_command.dart:22:26)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>

I'm using slidy 3.0.0

**Comment by jacobaraujo7** [comment]
Fixed!

**Comment by JacquesMarques** [comment]
Hi, I update to version 3.0.2 but the error persists. Can anyone help me with this?

**Comment by theolm** [comment]
Same here.
Any updates?

i'm using: 
slidy 3.0.2
dart  2.12.2
flutter 2.0.4
