### ISSUE TITLE
Error to start a project with `slidy start`

### ISSUE THREAD

**Issue by JonataCSantos** [Flutterando/slidy#276]
I'm running `slidy start` and no matter which option I choose to start, it ends with the same error:

```
Removing lib and test folders
Unhandled exception:
UnimplementedError
#0      CustomFile.writeAsString (package:slidy/src/core/models/custom_file.dart:251)
#1      new YamlServiceImpl (package:slidy/src/core/services/yaml_service_impl.dart:20)
#2      CreateImpl.call (package:slidy/src/modules/template_generator/domain/usecases/create.dart:28)
<asynchronous suspension>
#3      StartCommand.run (package:slidy/src/modules/template_generator/presentation/start_command.dart:122)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:209)
<asynchronous suspension>
#5      main (file:///private/tmp/slidy-20220824-11351-1qsps14/slidy-4.0.1/bin/main.dart:18)
<asynchronous suspension>
```

---

## System settings:

![image](https://user-images.githubusercontent.com/8602815/186654967-7b2be815-faf3-4bfa-9cf3-453652f40bbe.png)

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5.1 21G83 darwin-arm, locale en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.67.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

```
███████╗██╗     ██╗██████╗ ██╗   ██╗     ██████╗██╗     ██╗
██╔════╝██║     ██║██╔══██╗╚██╗ ██╔╝    ██╔════╝██║     ██║
███████╗██║     ██║██║  ██║ ╚████╔╝     ██║     ██║     ██║
╚════██║██║     ██║██║  ██║  ╚██╔╝      ██║     ██║     ██║
███████║███████╗██║██████╔╝   ██║       ╚██████╗███████╗██║
╚══════╝╚══════╝╚═╝╚═════╝    ╚═╝        ╚═════╝╚══════╝╚═╝                                             

CLI package manager and template for Flutter

Slidy version: 4.0.0+24
```

**Comment by francisco208** [comment]
I'm with exactly the same problem, slidy 4.0.1 windows 11

**Comment by luccacondratiuk** [comment]
same here
 - Slidy 4.0.1
 - Arch Linux
```
flutter --version
Flutter 3.1.0 • channel dev • https://github.com/flutter/flutter.git
Framework • revision bcea432bce (3 months ago) • 2022-05-26 09:05:34 -0700
Engine • revision 44e5b38ee8
Tools • Dart 2.18.0 (build 2.18.0-44.1.beta) • DevTools 2.12.2
```

**Comment by tairoroberto** [comment]
Same here

Slidy 4.0.1
Ubuntu 22.04.1 LTS

Flutter 3.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f1875d570e (7 weeks ago) • 2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2

**Comment by snowlzz** [comment]
Same here

Slidy 4.0.1
macOS Monterey 12.5.1

Flutter 3.0.5 - stable

Flutter doctor -v:

> ✓] Flutter (Channel stable, 3.3.0, on macOS 12.5.1 21G83 darwin-arm, locale
    pt-BR)
    • Flutter version 3.3.0 on channel stable at /Users/gabriel/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (4 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/gabriel/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Users/gabriel/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Android Slim SDK built for arm64 (mobile) • emulator-5554 • android-arm64
      • Android 11 (API 30) (emulator)
    • macOS (desktop)                           • macos         • darwin-arm64
      • macOS 12.5.1 21G83 darwin-arm
    • Chrome (web)                              • chrome        • web-javascript
      • Google Chrome 105.0.5195.52

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by jamesldr** [comment]
Same problem here. 
- Windows 11
- Flutter 3.3.0
- Slidy 4.0.1

**Comment by jamesldr** [comment]
solved in Slidy version 4.0.3

**Comment by ZIBMBRAZIL** [comment]
still continues with the error in slidey 4.0.3

![image](https://user-images.githubusercontent.com/13280820/190470981-5e235b2a-2ab1-4721-8915-05898abd7233.png)
